version: 2.1
defaults: &docker_image
  docker:
    - image: circleci/node:13.8.0

commands:
  print-out:
    parameters:
      input:
        type: string
        default: "Hello World"
    steps:
      - run: echo "<< parameters.input >>" > ~/output.txt


jobs:
  save_hello_world_output:
    <<: *docker_image
    steps:
      - print-out:
          input: "save_hello_world_output"
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    <<: *docker_image
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

  save_hello_to_cache:
    <<: *docker_image
    steps:
      - print-out
      - save_cache:
          key: myKey-{{ .Environment.MY_NAME }}
          paths:
            - ~/output.txt

  print_hello_from_cache:
    <<: *docker_image
    steps:
      - restore_cache:
          key: myKey-{{ .Environment.MY_NAME }}
      - run: cat ~/output.txt

  print_on_fail:
    <<: *docker_image
    steps:
      - run: exit 1
      - run:
          name: on error
          command: echo "Hellow Error"
          when: on_fail


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  first-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - save_hello_to_cache
      - print_hello_from_cache:
          requires:
            - save_hello_to_cache
      - print_on_fail
