version: 2.1
jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt

  save_hello_to_cache:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello world" > ~/output.txt
      - save_cache:
          key: myKey-{{ .Environment.MY_NAME }}
          paths:
            - ~/output.txt

  print_hello_from_cache:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - restore_cache:
          key: myKey-{{ .Environment.MY_NAME }}
      - run: cat ~/output.txt


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  first-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
      - save_hello_to_cache
      - print_hello_from_cache:
          requires:
            - save_hello_to_cache
